In [257]:
import numpy as np
import pandas as pd

In [258]:
# 25
df=pd.read_csv("out.csv")
step = 5
df = df.groupby(df.index//step).mean()
df.head(14)

        Real  Reci(k==0)        Sum  Real & Reci
0   0.000266    0.000058   0.000323     0.000122
1   0.002673    0.000494   0.003167     0.001277
2   0.003412    0.001508   0.004920     0.001976
3   0.002331    0.001224   0.003555     0.001959
4   0.001682    0.001278   0.002960     0.002971
5   0.003731    0.002805   0.006536     0.005847
6   0.013274    0.012451   0.025725     0.024494
7   0.049385    0.044656   0.094041     0.094320
8   0.198636    0.177742   0.376378     0.371772
9   0.780565    0.705256   1.485820     1.472683
10  1.224219    1.119828   2.344046     2.337231
11  3.416199    3.352695   6.768894     6.690664
12  5.544416    5.332934  10.877350    11.214036
13  8.286370    8.444015  16.730385    16.343578

In [259]:
# 35
df1=pd.read_csv("out2.csv")
step = 5
df1 = df1.groupby(df1.index//step).mean()
df1.head(20)

    # of atoms      Real  Reci(k==0)        Sum  Real & Reci
0          200  0.000328    0.000304   0.000633     0.000122
1          400  0.000553    0.001391   0.001944     0.002349
2          600  0.001440    0.000605   0.002045     0.001344
3          800  0.001771    0.000813   0.002584     0.001738
4         1000  0.001614    0.001422   0.003036     0.002750
5         1500  0.004258    0.002805   0.007063     0.005838
6         3000  0.015747    0.011237   0.026984     0.023477
7         6000  0.049552    0.044707   0.094258     0.093352
8        12000  0.207977    0.182842   0.390819     0.381608
9        15800  0.341483    0.314095   0.655578     0.648970
10       21800  0.645161    0.584600   1.229762     1.224781
11       27800  1.059692    0.977297   2.036989     2.058565
12       33800  1.652587    1.616909   3.269496     3.258190
13       39800  2.299644    2.242158   4.541802     4.520335
14       45800  3.050938    2.981400   6.032338     6.011042
15       51800  3.889348    3.798388   7.687737     7.665864
16       57800  4.858425    4.750344   9.608768     9.561455
17       63800  5.930780    5.794988  11.725768    11.696203
18       69800  7.056017    6.910464  13.966481    13.885875

In [260]:
# 45
df1=pd.read_csv("out3.csv")
step = 5
df1 = df1.groupby(df1.index//step).mean()
df1.head(20)

   # of atoms      Real  Reci(k==0)       Sum  Real & Reci
0         200  0.000210    0.000058  0.000267     0.000113
1         400  0.000806    0.000774  0.001580     0.001373
2         600  0.003335    0.001021  0.004356     0.002164
3         800  0.001720    0.000806  0.002526     0.001720
4        1000  0.001633    0.001374  0.003007     0.002813
5        1500  0.003656    0.003103  0.006759     0.005830
6        3000  0.012701    0.011228  0.023929     0.023670
7        6000  0.049993    0.044970  0.094963     0.094374
8       12000  0.197644    0.178319  0.375962     0.373348

In [261]:
# 50
df1=pd.read_csv("out5.csv")
step = 5
df1 = df1.groupby(df1.index//step).mean()
df1.head(25)

    # of atoms      Real  Reci(k==0)        Sum  Real & Reci
0          400  0.002470    0.000234   0.002705     0.000519
1          800  0.002325    0.001084   0.003409     0.002581
2         1000  0.001849    0.001576   0.003425     0.002620
3         1600  0.004146    0.003206   0.007353     0.006574
4         2000  0.005779    0.004978   0.010757     0.010594
5         2400  0.010189    0.007829   0.018017     0.017057
6         2800  0.011473    0.009595   0.021068     0.020200
7         3200  0.015594    0.012553   0.028147     0.026922
8         3600  0.017657    0.015890   0.033547     0.033441
9         3800  0.021601    0.018933   0.040534     0.037890
10        4000  0.028182    0.028869   0.057051     0.052840
11        9800  0.132922    0.121355   0.254277     0.248030
12       15800  0.349817    0.314722   0.664539     0.654506
13       21800  0.653325    0.590410   1.243735     1.257190
14       27800  1.082707    0.975484   2.058190     2.080548
15       33800  1.723742    1.653884   3.377626     3.424419
16       39800  2.347867    2.281036   4.628903     4.604790
17       45800  3.046793    2.966004   6.012796     5.988889
18       51800  3.896317    3.794940   7.691257     7.678541
19       57800  4.850350    4.727564   9.577914     9.529448
20       63800  5.914895    5.759999  11.674895    11.595287
21       69800  7.094671    6.914694  14.009365    13.916195

In [262]:
# 50
df1=pd.read_csv("out5new.csv")
step = 5
df1 = df1.groupby(df1.index//step).mean()
df1.head(25)

    # of atoms      Real  Reci(k==0)        Sum  Real & Reci
0          400  0.001523    0.000220   0.001743     0.000581
1          800  0.001338    0.001040   0.002378     0.003134
2         1000  0.001598    0.001597   0.003196     0.003481
3         1600  0.007196    0.003285   0.010480     0.008050
4         2000  0.006383    0.005195   0.011578     0.013281
5         2400  0.016580    0.017300   0.033880     0.025801
6         2800  0.012318    0.010475   0.022794     0.024853
7         3200  0.014953    0.012694   0.027647     0.032132
8         3600  0.017966    0.016321   0.034287     0.040460
9         3800  0.019779    0.018165   0.037944     0.044567
10        4000  0.028525    0.022903   0.051428     0.053932
11        9800  0.131469    0.119495   0.250963     0.301951
12       15800  0.345254    0.318796   0.664050     0.785305
13       21800  0.656906    0.608546   1.265451     1.486789
14       27800  1.077583    1.021363   2.098947     2.553385
15       33800  1.681600    1.651663   3.333263     4.007447
16       39800  2.354828    2.297238   4.652067     5.627462
17       45800  3.133604    3.035570   6.169174     7.438842
18       51800  3.893797    3.801857   7.695654     9.325270
19       57800  4.890853    4.842179   9.733031    11.804657
20       63800  5.951398    5.824984  11.776382    14.373810
21       69800  7.490917    7.222309  14.713226    17.364023

### Presentation on 15 Aug Data Tables
#### A. Real, B. Reciprocal(k==0)
#### 1. Separate loops for A and B
#### 2. Just Combine the A+B with same F_0 function
#### 3. Change F_0 which returns a vector
#### 4. Change F_0 which uses the deferencing of the output variables of modR and Dz
I will do this on the 50A cell

In [291]:
# 12, without threads
df1=pd.read_csv("aug15on50atoms_nothreads.csv")
step = 5
df1 = df1.groupby(df1.index//step).mean()
df1.head(25)

    # of atoms       Real  Reci(k==0)        Sum  Real & Reci
0          400   0.001883    0.001345   0.003228     0.003121
1          800   0.007028    0.005439   0.012467     0.012296
2         1000   0.010901    0.008100   0.019001     0.018821
3         1600   0.027887    0.021547   0.049435     0.049052
4         2000   0.044161    0.033829   0.077990     0.076724
5         2400   0.065460    0.050066   0.115526     0.114729
6         2800   0.087983    0.071424   0.159407     0.155695
7         3200   0.116936    0.088859   0.205796     0.195149
8         3600   0.141198    0.110125   0.251322     0.240478
9         3800   0.159186    0.119070   0.278256     0.269122
10        4000   0.175537    0.131879   0.307416     0.300629
11        9800   1.045214    0.800498   1.845712     1.795019
12       15800   2.751506    2.092257   4.843764     4.672891
13       21800   5.132292    3.940668   9.072960     8.830545
14       27800   8.519239    6.553943  15.073182    14.716612
15       33800  12.729213    9.606210  22.335423    21.900484
16       39800  17.311042   13.193866  30.504908    29.717762
17       45800  22.879880   17.337521  40.217401    39.107559
18       51800  29.320288   22.251301  51.571589    50.132409

In [292]:
# 12, with threads
df1=pd.read_csv("aug15on50atoms_threads.csv")
step = 5
df1 = df1.groupby(df1.index//step).mean()
df1.head(25)

    # of atoms      Real  Reci(k==0)       Sum  Real & Reci
0          400  0.000420    0.000330  0.000751     0.000909
1          800  0.004222    0.001566  0.005788     0.002747
2         1000  0.001634    0.001302  0.002937     0.003573
3         1600  0.003653    0.003144  0.006797     0.006941
4         2000  0.007029    0.005098  0.012127     0.010346
5         2400  0.009683    0.007170  0.016854     0.017909
6         2800  0.012010    0.010610  0.022620     0.021594
7         3200  0.025350    0.018142  0.043492     0.031916
8         3600  0.021683    0.016414  0.038097     0.033864
9         3800  0.020074    0.018029  0.038103     0.037732
10        4000  0.022277    0.020568  0.042845     0.041902
11        9800  0.138703    0.121110  0.259814     0.254031
12       15800  0.345497    0.311394  0.656891     0.658762
13       21800  0.647451    0.594078  1.241529     1.243276
14       27800  1.085171    0.993825  2.078996     2.071319
15       33800  1.714285    1.658809  3.373094     3.342891
16       39800  2.387011    2.327391  4.714401     4.686294
17       45800  3.094774    3.019663  6.114436     6.076426
18       51800  3.992574    3.851416  7.843989     7.779180

In [ ]:
# 13, without threads
df1=pd.read_csv("aug15on50atoms_nothreads2.csv")
step = 5
df1 = df1.groupby(df1.index//step).mean()
df1.head(25)

In [ ]:
# 13, with threads
df1=pd.read_csv("aug15on50atoms_threads2.csv")
step = 5
df1 = df1.groupby(df1.index//step).mean()
df1.head(25)

In [294]:
# 14, without threads
df1=pd.read_csv("aug15on50atoms_nothreads3.csv")
step = 5
df1 = df1.groupby(df1.index//step).mean()
df1.head(25)

    # of atoms       Real  Reci(k==0)        Sum  Real & Reci
0          400   0.002466    0.001755   0.004221     0.004125
1          800   0.007591    0.005694   0.013285     0.014305
2         1000   0.011754    0.008774   0.020528     0.022444
3         1600   0.030347    0.022811   0.053159     0.056490
4         2000   0.043065    0.033522   0.076587     0.084472
5         2400   0.064027    0.048354   0.112381     0.121022
6         2800   0.088818    0.067132   0.155950     0.166673
7         3200   0.116234    0.093926   0.210160     0.217327
8         3600   0.140183    0.109747   0.249930     0.266257
9         3800   0.158755    0.120726   0.279481     0.300231
10        4000   0.176371    0.134688   0.311059     0.333313
11        9800   1.046022    0.818935   1.864958     1.996208
12       15800   2.766788    2.093640   4.860428     5.192982
13       21800   5.158236    3.948977   9.107213     9.718892
14       27800   8.421301    6.413941  14.835243    15.850552
15       33800  12.456857    9.450590  21.907447    23.447915
16       39800  17.261062   13.127362  30.388424    32.529102
17       45800  22.833508   17.379151  40.212659    43.096665
18       51800  29.224191   22.239817  51.464009    55.047095

In [293]:
# 14, with threads
df1=pd.read_csv("aug15on50atoms_threads3.csv")
step = 5
df1 = df1.groupby(df1.index//step).mean()
df1.head(25)

    # of atoms      Real  Reci(k==0)       Sum  Real & Reci
0          400  0.000397    0.000219  0.000615     0.000493
1          800  0.002203    0.001704  0.003907     0.003567
2         1000  0.002105    0.001835  0.003940     0.003497
3         1600  0.004037    0.003300  0.007338     0.007155
4         2000  0.007590    0.005045  0.012635     0.010748
5         2400  0.008280    0.007052  0.015332     0.015302
6         2800  0.010828    0.009568  0.020396     0.021011
7         3200  0.019126    0.012773  0.031899     0.028450
8         3600  0.018084    0.016249  0.034334     0.034940
9         3800  0.020594    0.019409  0.040003     0.039019
10        4000  0.022065    0.020047  0.042112     0.043325
11        9800  0.132040    0.120144  0.252184     0.259863
12       15800  0.340504    0.315073  0.655577     0.682497
13       21800  0.649979    0.586104  1.236083     1.273983
14       27800  1.061294    0.953377  2.014670     2.121913
15       33800  1.693833    1.658148  3.351981     3.467132
16       39800  2.325020    2.273011  4.598030     4.733159
17       45800  3.125914    3.020860  6.146774     6.218083
18       51800  3.914490    3.789676  7.704166     7.902456